### ISSUE TITLE
Modify default cutoff settings during build

### ISSUE THREAD

**Issue by nistvan86** [nu774/fdkaac_autobuild#10]
It might probably not the best place to ask, but I'm using libfdk_aac.dll with foo_streamer and it uses the library's defaults for AAC-LC lowpass parameters, and provides no way to modify them.

What would it take to modify the default cutoffs during build, so I can create a custom library?

**Comment by nu774** [comment]
Well, It's apparently foo_streamer's problem not having enough interface for configuring encoder parameters that is already configurable through FDK-AAC API, and I really can't understand why you came here.

Having said that, if you desperately want to hack the libfdk-aac library itself, probably you can try editing aacEncDefaultConfig() function in aacend_lib.cpp

**Comment by nistvan86** [comment]
Sure thing, and sorry. I think foo_streamer is not maintained anymore and it's not open source. That's why I'm trying to solve it the other way around. Thanks for pointing to that function, I was searching for these values in the header files.
