### ISSUE TITLE
Cant download mingw-get-0.6.2-mingw32-beta-20131004-1-bin

### ISSUE THREAD

**Issue by n1v3k** [nu774/fdkaac_autobuild#5]
Hello there, Months ago I successfully did a build but lost the *.exe, so I decided to do another build but I'm getting this error:

```
retrieving http://sourceforge.net/projects/mingw/files/Installer/mingw-get/
retrieving http://sourceforge.net/projects/mingw/files/Installer/mingw-get/mingw
-get-0.6.2-beta-20131004-1/
retrieving http://sourceforge.net/projects/mingw/files/Installer/mingw-get/mingw
-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip/downl
oad
retrieving http://downloads.sourceforge.net/project/mingw/Installer/mingw-get/mi
ngw-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip?r=
&ts=1445142230&use_mirror=superb-dca2
C:\fdkaac_autobuild-master\install-mingw.js(86, 5) (null): The system cannot fin
d the file specified.
```

I'm on Win7 64 bit.
Thanks in advance.

**Comment by nu774** [comment]
Doesn't reproduce here.
Can you extract mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip in the folder  ? 
Do you see bin/mingw-get.exe in it?

**Comment by n1v3k** [comment]
I see the zip file but is corrupted its only 51 KB and there's not a \bin folder.

**Comment by nu774** [comment]
Is that 51kB file is HTML or something? Can you upload it?
It seem that URL in your log is correct. You can try manually enter the URL in web browers, and see what you get.

**Comment by n1v3k** [comment]
Yeah, the zip file its have html code in it or something, just opened in a text editor.
http://pastebin.com/KiV9sdcm#

**Comment by nu774** [comment]
Updated. install-mingw.bat now optionally accepts path name of mingw-get-*.zip. 

In case you still experience failure for some reason, please manually download mingw-get-*.zip from http://sourceforge.net/projects/mingw/files/Installer/mingw-get/mingw-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip/download,  and run install-mingw.bat like this:

```
C:\foo\bar> install-mingw.bat mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip
```

**Comment by n1v3k** [comment]
Cool, now its working, but now when its downloading packages from sourceforge, some of them didn't downloaded, maybe its the mirror from they were grabbed "prdownloads.sourceforge.net" anyway, this must be now a mirror issue, gonna try some other day, thanks for your time.
