### ISSUE TITLE
error during execution of build_libfdk_aac.bat

### ISSUE THREAD

**Issue by macsonya** [nu774/fdkaac_autobuild#6]
When I made a try to build fdk_aac.exe got an error message during execution of build_libfdk_aac.bat:

make: cc: Command not found
make: **\* [libfdk-aac-0.dll] Error 127

The mingw seems to be installed correctly, without any error message.
The problem exist (same) both on 32 and 64 bit edition of Windows 7 Professional .
I used the files from the most recent version of fdk-aac-master.zip downloaded from here.

**Comment by nu774** [comment]
Thanks for the report. Seems like recent MinGW gcc package doesn't include cc.exe (link to gcc.exe).
It's basically an issue on MinGW side, but updated to create hard link when cc.exe is not present. Try with the latest commit.

**Comment by macsonya** [comment]
I made a try with the new commit.
Of course, it works both cases (32bit/64bit Windows 7 Professional).
Perhaps it would be useful to write a notice in the "readme.txt", that the "install-mingw.bat" have to execute from an administrator command prompt (because using the fsutil utility).
If someone use double-click to run (like me) will not see the fsutil error message (need administrator privilege).
Finally I would like to thank for your effort.

**Comment by nu774** [comment]
Good points. Have changed to use copy instead.
