### ISSUE TITLE
error building libfdk_aac

### ISSUE THREAD

**Issue by mobile999** [nu774/fdkaac_autobuild#8]
I get this error message during execution of build_libfdk_aac.bat on Windows 10 64-bit:

make: **\* No rule to make target `libAACenc/src/aacenc_hcr.o', needed by`libfdk-aac.a'.  Stop.

**Comment by nu774** [comment]
Thanks for reporting, aacenc_hcr.cpp was renamed on the recent libfdk-aac update.
Fixed it now.

**Comment by mobile999** [comment]
Now I get:

d:/fdkaac_autobuild-master/bin/../lib/gcc/mingw32/5.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
make: **\* [libfdk-aac-0.dll] Error 1

**Comment by nu774** [comment]
Thanks, should be fixed now.
